baseurl: https://noetel.com.au/
title: Dr Michael Noetel
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: 'G-GE7K0MXWFF'
params:
  copyright: '&copy;2022 Michael Noetel'
  description: Dr Michael Noetel
  email: ""
  navlinks:
    - home: yes
      name: Home
      url: projects/
    - name: Resume
      url: /mnoetel_resume.html
    - name: Get in touch
      url: contact/
  sidebarAbout:
    - <img src="/./config_files/mnoetel_circle.png" alt="Michael Noetel Round Profile Picture" width="50%"/>
    - Michael is a psychologist and an academic trying to find the best ways of helping others, and to then put them into practice. He’s an awarded educator, including awards from the Australian Awards for University teaching. He’s a prolific early career researcher with over <a href = "https://scholar.google.com.au/citations?hl=en&user=RAe4W2QAAAAJ">30 publications in the last 4 years</a>. He’s a <a href="http://researchers.uq.edu.au/researcher/37507">Senior Lecturer in the School of Psychology at the University of Queensland</a> and is the Chair of <a href="http://eaa.org.au/">Effective Altruism Australia</a>, a charity trying to help Australian donors to do the most good with their donations.
    - Originally from Sydney but fell in love with a Queenslander. Proud dad of two gorgeous rugrats.
  social:
    email: noetel@gmail.com
    youtube: "https://www.youtube.com/c/NoetelAu/"
    twitter: "https://twitter.com/mnoetel"
  style: "red"

markup:
  goldmark:
    renderer:
      unsafe: true
