baseurl: https://noetel.com.au/
title: Dr Michael Noetel
theme: hugo-creative-portfolio-theme
languageCode: en-us
disqusShortname: ''
googleAnalytics: 'G-GE7K0MXWFF'
params:
  copyright: '&copy;2022 Michael Noetel'
  description: Dr Michael Noetel, Researcher, Teacher, Performance Psychologist, Longtermist, Effective Altruist
  email: ""
  navlinks:
    - home: yes
      name: Home
      url: projects/
    - name: Resume
      url: /mnoetel_resume.pdf
    - name: Get in touch
      url: contact/
  sidebarAbout:
    - <img src="/./config_files/mnoetel_circle.png" alt="Michael Noetel Round Profile Picture" width="50%"/>
    - I'm an academic, performance psychologist, longtermist, and effective altruist. I want to work on protecting future generations. I do that by creating effective, scalable educational programs. That content is designed to help people make better decisions, become more empathic, and more effective in their work (esp. their research). See my <a href="https://scholar.google.com.au/citations?hl=en&user=RAe4W2QAAAAJ">publications here</a>.
    - Originally from Sydney but fell in love with a Queenslander. Proud dad of two gorgeous rugrats.
  social:
    email: noetel@gmail.com
    youtube: "https://www.youtube.com/c/NoetelAu/"
    twitter: "https://twitter.com/mnoetel"
  style: "red"

markup:
  goldmark:
    renderer:
      unsafe: true
