---
date: "2022-08-18T13:00:25+05:30"
title: Get in touch
---

#### I'm currently focusing on

-   Safely navigating the transition to a world with powerful Artificial Intelligence
-   Using Artificial Intelligence to increase learning
-   Training young people to tackle the world's most pressing problems, like existential risks
-   Improving ethical reasoning and rationality at scale

#### I might be able to help you by:

-   Creating evidence-based online learning design, and engaging, effective training programs
-   Conducting efficient, effective, and robust systematic reviews / overviews of reviews
-   Running sophisticated meta-analytic techniques like network meta-analysis or <a href = "https://cran.r-project.org/web/packages/metaSEM/vignettes/Examples.html">meta-analytic structural equation models</a>
-   Being an <a href = "https://www.nature.com/articles/d41586-019-01184-9">agile</a>, autonomy supportive <a href = "https://psycnet.apa.org/record/2018-24069-001">leader</a> and <a href = "https://www.sciencedirect.com/science/article/abs/pii/S0001879120300841">supervisor</a>

The best way to get in contact is via <a href = "mailto: noetel@gmail.com">email</a>.